--- 
apiVersion: v1
kind: Service
metadata: 
  annotations: 
    prometheus.io/port: "9100"
    prometheus.io/scrape: "true"
  name: node-exporter
  namespace: default
spec: 
  ports: 
    - 
      name: node-exporter
      nodePort: 32100
      port: 9100
      protocol: TCP
      targetPort: 32100
  selector: 
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
  type: NodePort
